fullnameOverride: ipam-capi
webhook:
  enable: "true"
webhookInjector:
  repository: keppel.global.cloud.sap/ccloud-ghcr-io-mirror/SAP-cloud-infrastructure/webhook-injector
  tag: latest
controllerManager:
  manager:
    env:
      KUBECONFIG: "/var/run/remote-kubeconfig/kubeconfig"
    volumes:
      - name: webhook-certs
        mountPath: /tmp/k8s-webhook-server/serving-certs
        readOnly: true
        source:
          emptyDir: {}
      - name: remote-serviceaccount
        mountPath: /var/run/secrets/kubernetes.io/remote-serviceaccount
        readOnly: true
        source:
          secret:
            secretName: ipam-capi-remote-kubeconfig
            items:
              - key: token
                path: token
              - key: bundle.crt
                path: ca.crt
      - name: remote-kubeconfig
        mountPath: /var/run/remote-kubeconfig
        readOnly: true
        source:
          configMap:
            name: ipam-capi-remote-kubeconfig
  podSecurityContext:
    runAsUser: 65532 # ensure sidecar and main controller run as same user, so they can share generated tls certs via emptyDir volume 
    runAsGroup: 65532
